### ISSUE TITLE
Fix up CountdownTimer model names

### ISSUE THREAD

**Issue by bryce13950** [PomeloProductions/countdown#1]
Right now there are conflicting names in the model. The table name is wp_countdown_timer_entries, which contains the namespace for WordPress as well as the plugin, and the remaining would equate to a model name of TimeEntry. The actual model name is CountdownTimer, which would imply a table name of wp_countdown_countdown_timers.

In any model system the model name should be singular version of the table name. In the case specifically the namespaces are not considered to be part of the normal table name. You name spaces are `wp` for the global wordpress name space, and `countdown` for the plugin name space.

The name of this model needs to be fixed up in some way, or else future additions to WordWrap will make this harder to manage as automated name generation is added. I prefer the name Timer, since Entry is a bit redundant and prefixing the table name with the exact same thing as the plugin namespace is also a bit redundant.

**Comment by Quixotical** [comment]
changed table name to wp_countdown_timers and changed model to Timer. Also updated all references to table & renamed class.
