### ISSUE TITLE
Remove model fetchAll function

### ISSUE THREAD

**Issue by bryce13950** [PomeloProductions/countdown#10]
There is a function in BaseModel that fetches everything. It does not currently check against a deleted_at field, but instead of adding a nearly identical function to the child model you should just modify the parent function to check against the deleted_at field.

**Comment by bryce13950** [comment]
The BaseModel function is named all

**Comment by Quixotical** [comment]
ok, i had been under the impression that for this plugin, I should not be changing the functionality of any other plugins to make it work, so I think I probably just thought this was the best way to do it
