### ISSUE TITLE
Display date while handling short code

### ISSUE THREAD

**Issue by bryce13950** [PomeloProductions/countdown#12]
The short code needs to display the date with progressively less information. If there are more than 10 days remaining we will only show days. If there are more than 3 days remaining then we will show days and hours. If there is more than an hour remaining then we will show hours and minutes. Within the last hour we will only show minutes. After the timer has passed we need to make sure that nothing is shown.

**Comment by Quixotical** [comment]
this task has been partially completed. It does not make progressive changes, but the date does appear on the page now. I am stopping work on this for now per Bryce's request.

**Comment by bryce13950** [comment]
Yeah, my bad the original purpose of this for 0.1.0 was to simply display the date. The 0.2.x milestone is going to be for making it display properly.

**Comment by Quixotical** [comment]
ok, good.
