### ISSUE TITLE
ShortCode - add function for getting display text

### ISSUE THREAD

**Issue by bryce13950** [PomeloProductions/countdown#17]
There should be a function built that will take a DateTime and then determine the proper display text until the actual date time. This could be accomplished pretty easily by doing something like this.

```
// Create the DateDiff object
switch(true) {
    case $rangeLogicHere: //use DateDiff object to determine if within biggest range
        return " " . $days . " days left";
    ...
    case $rangeLogicHere: //use DateDiff object to determine if within smallest range
        return " " . $seconds . " seconds left";
    default:
        return "";//return empty string if the date has passed.

}
```

**Comment by Quixotical** [comment]
done. Everything is formatted from years down to only seconds remaining. I understand years might be a bit overkill, but if after a convention the next one is a year + 1 weekend later or something, I thought it would be good to show that.. besides it didn't take long to format.
